/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataAnalyse: typeof import('./src/components/dataAnalyse.vue')['default']
    DataAnalysis: typeof import('./src/components/dataAnalysis.vue')['default']
    HeaderMenu: typeof import('./src/components/headerMenu.vue')['default']
    MainMenu: typeof import('./src/components/mainMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrackingMachine: typeof import('./src/components/trackingMachine.vue')['default']
  }
}
